# based on example at https://w3c.github.io/spec-prod/#multiple-specs-in-same-repository
name: Build Specifications
on:
  pull_request: {}
  push:
    branches: [main]
    paths:
      - '*.bs'
      - 'resources/*.ttl'
      - '.github/workflows/auto-publish.yml'
  workflow_dispatch: {}

jobs:
  main:
    name: Build, validate and deploy specs drafted in Bikeshed
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    strategy:
      max-parallel: 1
      matrix:
        include:
          - source: policy.bs
          - source: data_exchange.bs
          - source: discovery.bs
          - source: course_identifier.bs
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: getdate
        name: Get date of last commit
        run: echo "date=$(git log -n 1 --format=%as -- ${{ matrix.source }})" >> $GITHUB_OUTPUT
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: ${{ matrix.source }}
          TOOLCHAIN: bikeshed
          GH_PAGES_BRANCH: gh-pages
          GH_PAGES_BUILD_OVERRIDE: "date: ${{ steps.getdate.outputs.date }}"

  copy-resources:
    name: Convert RDF files, generate documentation and copy to gh-pages
    needs: main
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          path: main-branch
      
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages-branch

      - name: Install RDFlib
        run: python -m pip install rdflib

      - name: Convert Turtle to JSON-LD, RDF+XML and N-Triples
        run: |
          for infile in main-branch/resources/*.ttl ; do
            python -m rdflib.tools.rdfpipe -i turtle -o json-ld $infile > main-branch/resources/`basename -s .ttl $infile`.json
            python -m rdflib.tools.rdfpipe -i turtle -o xml $infile > main-branch/resources/`basename -s .ttl $infile`.rdf
            python -m rdflib.tools.rdfpipe -i turtle -o nt11 $infile > main-branch/resources/`basename -s .ttl $infile`.nt
          done

      - name: Cache SHACL Play app
        uses: actions/cache@v4
        with:
          path: ~/shacl-play.jar
          key: shacl-play-0.10.1

      - name: Install SHACL Play app
        run: |
          sudo apt-get -y update && \
          sudo apt-get -y install graphviz && \
          test -f ~/shacl-play.jar || curl -L -o ~/shacl-play.jar "https://github.com/sparna-git/shacl-play/releases/download/0.10.1/shacl-play-app-0.10.1-onejar.jar"

      - name: Generate HTML from SHACL
        run: |
          for infile in main-branch/resources/*.ttl ; do
            GRAPHVIZ_DOT=/usr/bin/dot java -jar ~/shacl-play.jar doc -i $infile -l en -o main-branch/resources/`basename -s .ttl $infile`.html
          done

      - name: Cache WIDOCO app
        uses: actions/cache@v4
        with:
          path: ~/widoco.jar
          key: widoco-1.4.25

      - name: Install WIDOCO app
        run: |
          test -f ~/widoco.jar || curl -L -o ~/widoco.jar "https://github.com/dgarijo/Widoco/releases/download/v1.4.25/widoco-1.4.25-jar-with-dependencies_JDK-17.jar"

      - name: Generate ontology documentation
        run: |
          java -jar ~/widoco.jar -ontFile main-branch/resources/ontology-shacl.ttl -uniteSections -outFolder widoco-out -excludeProvenance && \
          mkdir -p gh-pages-branch/resources/resources && \
          mv -v widoco-out/index-en.html gh-pages-branch/resources/ontology.html && \
          rsync -auv widoco-out/resources/ gh-pages-branch/resources/resources/

      - name: Deploy to gh-pages
        run: |
          cd main-branch
          git config --global user.name "$(git show -s --format='%an' $GITHUB_SHA)"
          git config --global user.email "$(git show -s --format='%ae' $GITHUB_SHA)"
          git show -s --format=%s $GITHUB_SHA > /tmp/COMMIT_MSG
          cd ..
          rsync -auv main-branch/resources/ gh-pages-branch/resources/
          cd gh-pages-branch
          cp -v resources/ontology-shacl.ttl resources/ontology.ttl
          cp -v resources/ontology-shacl.json resources/ontology.jsonld
          cp -v resources/ontology-shacl.rdf resources/ontology.owl
          cp -v resources/ontology-shacl.nt resources/ontology.nt
          git add resources/
          git commit -F /tmp/COMMIT_MSG || echo "No changes to commit"
          git push
