# based on example at https://w3c.github.io/spec-prod/#multiple-specs-in-same-repository
name: Build Specifications
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  main:
    name: Build, validate and deploy specs drafted in Bikeshed
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      max-parallel: 1
      matrix:
        include:
          - source: policy.bs
          - source: data_exchange.bs
          - source: discovery.bs
    steps:
      - uses: actions/checkout@v4
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: ${{ matrix.source }}
          TOOLCHAIN: bikeshed
          GH_PAGES_BRANCH: gh-pages

  copy-resources:
    name: Convert RDF files, generate documentation and copy to gh-pages
    needs: main
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          path: main-branch
      
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages-branch

      - name: Convert Turtle to JSON-LD and RDF+XML
        run: |
          python -m pip install rdflib && \
          for infile in main-branch/resources/*.ttl ; do
            python -m rdflib.tools.rdfpipe -i turtle -o json-ld $infile > main-branch/resources/`basename -s .ttl $infile`.json
            python -m rdflib.tools.rdfpipe -i turtle -o xml $infile > main-branch/resources/`basename -s .ttl $infile`.rdf
          done

      - name: Generate HTML from SHACL
        run: |
          curl -L -o shacl-play.jar "https://github.com/sparna-git/shacl-play/releases/download/0.9.0/shacl-play-app-0.9.0-onejar.jar" && \
          for infile in main-branch/resources/*.ttl ; do java -jar shacl-play.jar doc -d -i $infile -l en -o main-branch/resources/`basename -s .ttl $infile`.html ; done

      - name: Copy resources directory
        run: |
          cp -r main-branch/resources gh-pages-branch/
          cd gh-pages-branch
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add resources/
          git commit -m "Update resources directory" || echo "No changes to commit"
          git push
