# based on example at https://w3c.github.io/spec-prod/#multiple-specs-in-same-repository
name: Build Specifications
on:
  pull_request: {}
  push:
    branches: [main]
    paths:
      - '*.bs'
      - 'resources/*.ttl'
  workflow_dispatch: {}

jobs:
  main:
    name: Build, validate and deploy specs drafted in Bikeshed
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    strategy:
      max-parallel: 1
      matrix:
        include:
          - source: policy.bs
          - source: data_exchange.bs
          - source: discovery.bs
    steps:
      - uses: actions/checkout@v4
      - id: getdate
        name: Get date of last commit
        run: echo "date=$(git log -n 1 --format=%as -- ${{ matrix.source }})" >> $GITHUB_OUTPUT
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: ${{ matrix.source }}
          TOOLCHAIN: bikeshed
          GH_PAGES_BRANCH: gh-pages
          GH_PAGES_BUILD_OVERRIDE: "date: ${{ steps.getdate.outputs.date }}"

  copy-resources:
    name: Convert RDF files, generate documentation and copy to gh-pages
    needs: main
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          path: main-branch
      
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages-branch

      - name: Install RDFlib
        run: python -m pip install rdflib

      - name: Convert Turtle to JSON-LD and RDF+XML
        run: |
          for infile in main-branch/resources/*.ttl ; do
            python -m rdflib.tools.rdfpipe -i turtle -o json-ld $infile > main-branch/resources/`basename -s .ttl $infile`.json
            python -m rdflib.tools.rdfpipe -i turtle -o xml $infile > main-branch/resources/`basename -s .ttl $infile`.rdf
          done

      - name: Cache SHACL Play app
        uses: actions/cache@v4
        with:
          path: ~/shacl-play.jar
          key: shacl-play-0.9.0

      - name: Install SHACL Play app
        run: |
          sudo apt-get -y update && \
          sudo apt-get -y install graphviz && \
          test -f ~/shacl-play.jar || curl -L -o ~/shacl-play.jar "https://github.com/sparna-git/shacl-play/releases/download/0.9.0/shacl-play-app-0.9.0-onejar.jar"

      - name: Generate HTML from SHACL
        run: |
          for infile in main-branch/resources/*.ttl ; do
            GRAPHVIZ_DOT=/usr/bin/dot java -jar ~/shacl-play.jar doc -d -i $infile -l en -o main-branch/resources/`basename -s .ttl $infile`.html
          done

      - name: Copy resources directory
        run: |
          cp -r main-branch/resources gh-pages-branch/
          cd gh-pages-branch
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add resources/
          git commit -m "Update resources directory" || echo "No changes to commit"
          git push
