# based on example at https://w3c.github.io/spec-prod/#multiple-specs-in-same-repository
name: Build Specifications
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      max-parallel: 1
      matrix:
        include:
          - source: policy.bs
          - source: data_exchange.bs
          - source: discovery.bs
    steps:
      - uses: actions/checkout@v4
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: ${{ matrix.source }}
          TOOLCHAIN: bikeshed
          GH_PAGES_BRANCH: gh-pages

  copy-resources:
    name: Copy Resources to GH Pages
    needs: main
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          path: main-branch
      
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages-branch
      
      - name: Copy resources directory
        run: |
          cp -r main-branch/resources gh-pages-branch/
          cd gh-pages-branch
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add resources/
          git commit -m "Update resources directory" || echo "No changes to commit"
          git push